In [1]:
import pandas as pd

# DataFrame 인덱싱

## 인덱싱

In [3]:
iphone_df = pd.read_csv('./data/iphone.csv', index_col = 0)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [4]:
iphone_df.loc['iPhone 8','메모리']

'2GB'

In [5]:
iphone_df.loc['iPhone X', :]

출시일        2017-11-03
디스플레이             5.8
메모리               3GB
출시 버전        iOS 11.1
Face ID           Yes
Name: iPhone X, dtype: object

In [6]:
iphone_df.loc[:,'출시일']

iPhone 7         2016-09-16
iPhone 7 Plus    2016-09-16
iPhone 8         2017-09-22
iPhone 8 Plus    2017-09-22
iPhone X         2017-11-03
iPhone XS        2018-09-21
iPhone XS Max    2018-09-21
Name: 출시일, dtype: object

In [9]:
iphone_df['출시일']

iPhone 7         2016-09-16
iPhone 7 Plus    2016-09-16
iPhone 8         2017-09-22
iPhone 8 Plus    2017-09-22
iPhone X         2017-11-03
iPhone XS        2018-09-21
iPhone XS Max    2018-09-21
Name: 출시일, dtype: object

In [10]:
type(iphone_df['출시일'])

pandas.core.series.Series

In [7]:
iphone_df.loc[['iPhone X', 'iPhone 8']]

                 출시일  디스플레이  메모리     출시 버전 Face ID
iPhone X  2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone 8  2017-09-22    4.7  2GB  iOS 11.0      No

In [8]:
type(iphone_df.loc[['iPhone X', 'iPhone 8']])

pandas.core.frame.DataFrame

## 슬라이싱

In [11]:
iphone_df[['Face ID','출시일', '메모리']]

              Face ID         출시일  메모리
iPhone 7           No  2016-09-16  2GB
iPhone 7 Plus      No  2016-09-16  3GB
iPhone 8           No  2017-09-22  2GB
iPhone 8 Plus      No  2017-09-22  3GB
iPhone X          Yes  2017-11-03  3GB
iPhone XS         Yes  2018-09-21  4GB
iPhone XS Max     Yes  2018-09-21  4GB

In [12]:
iphone_df.loc['iPhone 8': 'iPhone XS']

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes

## 조건

In [13]:
iphone_df.loc[[True, False, True, True, False, True, False]]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes

In [14]:
iphone_df['디스플레이'] > 5

iPhone 7         False
iPhone 7 Plus     True
iPhone 8         False
iPhone 8 Plus     True
iPhone X          True
iPhone XS         True
iPhone XS Max     True
Name: 디스플레이, dtype: bool

In [15]:
iphone_df.loc[iphone_df['디스플레이']>5]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [16]:
iphone_df['Face ID'] == 'Yes'

iPhone 7         False
iPhone 7 Plus    False
iPhone 8         False
iPhone 8 Plus    False
iPhone X          True
iPhone XS         True
iPhone XS Max     True
Name: Face ID, dtype: bool

In [17]:
iphone_df.loc[iphone_df['Face ID']=='Yes']

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [18]:
(iphone_df['디스플레이']>5)&(iphone_df['Face ID']=='Yes')

iPhone 7         False
iPhone 7 Plus    False
iPhone 8         False
iPhone 8 Plus    False
iPhone X          True
iPhone XS         True
iPhone XS Max     True
dtype: bool

In [19]:
condition = (iphone_df['디스플레이']>5)&(iphone_df['Face ID']=='Yes')
iphone_df[condition]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [20]:
condition = (iphone_df['디스플레이']>5) | (iphone_df['Face ID']=='Yes')
iphone_df[condition]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

## 인덱스

In [21]:
iphone_df.iloc[2,4]

'No'

In [22]:
iphone_df.iloc[[1,3],[1,4]]

               디스플레이 Face ID
iPhone 7 Plus    5.5      No
iPhone 8 Plus    5.5      No

In [23]:
iphone_df.iloc[3:,1:4]

               디스플레이  메모리     출시 버전
iPhone 8 Plus    5.5  3GB  iOS 11.0
iPhone X         5.8  3GB  iOS 11.1
iPhone XS        5.8  4GB  iOS 12.0
iPhone XS Max    6.5  4GB  iOS 12.0

## 정리

### 이름으로 인덱싱하기


하나의 row 이름	df.loc["row4"]


row 이름의 리스트	df.loc[["row4", "row5", "row3"]]


row 이름의 리스트 슬라이싱	df.loc["row2":"row5"]	df["row2":"row5"]


하나의 column 이름	df.loc[:, "col1"]	df["col1"]


column 이름의 리스트	df.loc[:, ["col4", "col6", "col3"]]	df[["col4", "col6", "col3"]]


column 이름의 리스트 슬라이싱	df.loc[:, "col2":"col5"]

### 위치로 인덱싱하기


하나의 row 위치	df.iloc[8]	


row 위치의 리스트	df.iloc[[4, 5, 3]]	


row 위치의 리스트 슬라이싱	df.iloc[2:5]	df[2:5]


하나의 column 위치	df.iloc[:, 3]	


column 위치의 리스트	df.iloc[:, [3, 5, 6]]	


column 위치의 리스트 슬라이싱	df.iloc[:, 3:7]

# 데이터 변형

## 작은 데이터

### 단일 변경

In [24]:
import pandas as pd

In [26]:
iphone_df = pd.read_csv('./data/iphone.csv', index_col=0)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [27]:
iphone_df.loc['iPhone 8'] = ['2016-02-18', '88', '10GB',"ios 20.0","No"]
iphone_df

                      출시일 디스플레이   메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7   2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16   5.5   3GB  iOS 10.0      No
iPhone 8       2016-02-18    88  10GB  ios 20.0      No
iPhone 8 Plus  2017-09-22   5.5   3GB  iOS 11.0      No
iPhone X       2017-11-03   5.8   3GB  iOS 11.1     Yes
iPhone XS      2018-09-21   5.8   4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21   6.5   4GB  iOS 12.0     Yes

In [28]:
iphone_df["디스플레이"] = ['in', 'in','in','in','in','in','in']
iphone_df

                      출시일 디스플레이   메모리     출시 버전 Face ID
iPhone 7       2016-09-16    in   2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    in   3GB  iOS 10.0      No
iPhone 8       2016-02-18    in  10GB  ios 20.0      No
iPhone 8 Plus  2017-09-22    in   3GB  iOS 11.0      No
iPhone X       2017-11-03    in   3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    in   4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    in   4GB  iOS 12.0     Yes

In [30]:
iphone_df['Face ID'] = ["No", "No", "No", "No", "No", "No", "No"]
iphone_df

                      출시일 디스플레이   메모리     출시 버전 Face ID
iPhone 7       2016-09-16    in   2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    in   3GB  iOS 10.0      No
iPhone 8       2016-02-18    in  10GB  ios 20.0      No
iPhone 8 Plus  2017-09-22    in   3GB  iOS 11.0      No
iPhone X       2017-11-03    in   3GB  iOS 11.1      No
iPhone XS      2018-09-21    in   4GB  iOS 12.0      No
iPhone XS Max  2018-09-21    in   4GB  iOS 12.0      No

In [31]:
iphone_df["Face ID"] = 'Yes'
iphone_df

                      출시일 디스플레이   메모리     출시 버전 Face ID
iPhone 7       2016-09-16    in   2GB  iOS 10.0     Yes
iPhone 7 Plus  2016-09-16    in   3GB  iOS 10.0     Yes
iPhone 8       2016-02-18    in  10GB  ios 20.0     Yes
iPhone 8 Plus  2017-09-22    in   3GB  iOS 11.0     Yes
iPhone X       2017-11-03    in   3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    in   4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    in   4GB  iOS 12.0     Yes

### 여러 행 변경

In [32]:
import pandas as pd

In [33]:
iphone_df = pd.read_csv('./data/iphone.csv', index_col=0)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [34]:
iphone_df[['디스플레이', 'Face ID']] = 'X'
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16     X  2GB  iOS 10.0       X
iPhone 7 Plus  2016-09-16     X  3GB  iOS 10.0       X
iPhone 8       2017-09-22     X  2GB  iOS 11.0       X
iPhone 8 Plus  2017-09-22     X  3GB  iOS 11.0       X
iPhone X       2017-11-03     X  3GB  iOS 11.1       X
iPhone XS      2018-09-21     X  4GB  iOS 12.0       X
iPhone XS Max  2018-09-21     X  4GB  iOS 12.0       X

In [35]:
iphone_df[['디스플레이', 'Face ID']] = 'X', 'H'
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16     X  2GB  iOS 10.0       H
iPhone 7 Plus  2016-09-16     X  3GB  iOS 10.0       H
iPhone 8       2017-09-22     X  2GB  iOS 11.0       H
iPhone 8 Plus  2017-09-22     X  3GB  iOS 11.0       H
iPhone X       2017-11-03     X  3GB  iOS 11.1       H
iPhone XS      2018-09-21     X  4GB  iOS 12.0       H
iPhone XS Max  2018-09-21     X  4GB  iOS 12.0       H

In [36]:
iphone_df.loc[['iPhone 7', 'iPhone X']] = 'O'
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7                O     O    O         O       O
iPhone 7 Plus  2016-09-16     X  3GB  iOS 10.0       H
iPhone 8       2017-09-22     X  2GB  iOS 11.0       H
iPhone 8 Plus  2017-09-22     X  3GB  iOS 11.0       H
iPhone X                O     O    O         O       O
iPhone XS      2018-09-21     X  4GB  iOS 12.0       H
iPhone XS Max  2018-09-21     X  4GB  iOS 12.0       H

In [37]:
iphone_df.loc['iPhone 7' : 'iPhone X'] = "B"
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7                B     B    B         B       B
iPhone 7 Plus           B     B    B         B       B
iPhone 8                B     B    B         B       B
iPhone 8 Plus           B     B    B         B       B
iPhone X                B     B    B         B       B
iPhone XS      2018-09-21     X  4GB  iOS 12.0       H
iPhone XS Max  2018-09-21     X  4GB  iOS 12.0       H

In [38]:
import pandas as pd

In [39]:
iphone_df = pd.read_csv('./data/iphone.csv', index_col=0)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [42]:
iphone_df.loc[iphone_df['디스플레이']>5] = 'p'
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0      No
iPhone 7 Plus           p     p    p         p       p
iPhone 8       2017-09-22   4.7  2GB  iOS 11.0      No
iPhone 8 Plus           p     p    p         p       p
iPhone X                p     p    p         p       p
iPhone XS               p     p    p         p       p
iPhone XS Max           p     p    p         p       p

In [43]:
iphone_df.iloc[[1,3],[1,4]] = 'S'
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0      No
iPhone 7 Plus           p     S    p         p       S
iPhone 8       2017-09-22   4.7  2GB  iOS 11.0      No
iPhone 8 Plus           p     S    p         p       S
iPhone X                p     p    p         p       p
iPhone XS               p     p    p         p       p
iPhone XS Max           p     p    p         p       p

### 데이터 추가

In [44]:
iphone_df = pd.read_csv('./data/iphone.csv', index_col=0)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [45]:
iphone_df.loc['iphone XR'] = ['2018-02-18', 8.8, '3GB', 'ios 12.0.8', 'Yes']
iphone_df

                      출시일  디스플레이  메모리       출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB    iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB    iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB    iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB    iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB    iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB    iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB    iOS 12.0     Yes
iphone XR      2018-02-18    8.8  3GB  ios 12.0.8     Yes

In [46]:
iphone_df['제조사'] = 'Apple'
iphone_df

                      출시일  디스플레이  메모리       출시 버전 Face ID    제조사
iPhone 7       2016-09-16    4.7  2GB    iOS 10.0      No  Apple
iPhone 7 Plus  2016-09-16    5.5  3GB    iOS 10.0      No  Apple
iPhone 8       2017-09-22    4.7  2GB    iOS 11.0      No  Apple
iPhone 8 Plus  2017-09-22    5.5  3GB    iOS 11.0      No  Apple
iPhone X       2017-11-03    5.8  3GB    iOS 11.1     Yes  Apple
iPhone XS      2018-09-21    5.8  4GB    iOS 12.0     Yes  Apple
iPhone XS Max  2018-09-21    6.5  4GB    iOS 12.0     Yes  Apple
iphone XR      2018-02-18    8.8  3GB  ios 12.0.8     Yes  Apple

### 데이터 제거

In [47]:
iphone_df.drop('iphone XR', axis = 'index', inplace=True)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID    제조사
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No  Apple
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No  Apple
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No  Apple
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No  Apple
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes  Apple
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes  Apple
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes  Apple

In [48]:
iphone_df.drop('제조사', axis = 'columns', inplace=True)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [49]:
iphone_df.drop(['iPhone 7', 'iPhone 8', 'iPhone X'], axis = 'index', inplace=True)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

## 큰 데이터

### 개요

In [50]:
import pandas as pd

In [52]:
laptops_df = pd.read_csv('./data/laptops.csv')
laptops_df

,brand,model,ram,hd_type,hd_size,screen_size,price,processor_brand,processor_model,clock_speed,graphic_card_brand,graphic_card_size,os,weight,comments
0,Dell,Inspiron 15-3567,4,hdd,1024,15.6,40000,intel,i5,2.5,intel,NaN,linux,2.50,NaN
1,Apple,MacBook Air,8,ssd,128,13.3,55499,intel,i5,1.8,intel,2.0,mac,1.35,NaN
2,Apple,MacBook Air,8,ssd,256,13.3,71500,intel,i5,1.8,intel,2.0,mac,1.35,NaN
3,Apple,MacBook Pro,8,ssd,128,13.3,96890,intel,i5,2.3,intel,2.0,mac,3.02,NaN
4,Apple,MacBook Pro,8,ssd,256,13.3,112666,intel,i5,2.3,intel,2.0,mac,3.02,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,Asus,A555LF,8,hdd,1024,15.6,39961,intel,i3 4th gen,1.7,nvidia,2.0,windows,2.30,NaN
163,Asus,X555LA-XX172D,4,hdd,500,15.6,28489,intel,i3 4th gen,1.9,intel,NaN,linux,2.30,NaN
164,Asus,X554LD,2,hdd,500,15.6,29199,intel,i3 4th gen,1.9,intel,1.0,linux,2.30,NaN
165,Asus,X550LAV-XX771D,2,hdd,500,15.6,29990,intel,i3 4th gen,1.7,intel,NaN,linux,2.50,NaN
166,Asus,X540LA-XX538T,4,hdd,1024,15.6,30899,intel,i3 5th gen,2.0,intel,NaN,windows,2.30,NaN

In [53]:
laptops_df.head(3)

,brand,model,ram,hd_type,hd_size,screen_size,price,processor_brand,processor_model,clock_speed,graphic_card_brand,graphic_card_size,os,weight,comments
0,Dell,Inspiron 15-3567,4,hdd,1024,15.6,40000,intel,i5,2.5,intel,NaN,linux,2.50,NaN
1,Apple,MacBook Air,8,ssd,128,13.3,55499,intel,i5,1.8,intel,2.0,mac,1.35,NaN
2,Apple,MacBook Air,8,ssd,256,13.3,71500,intel,i5,1.8,intel,2.0,mac,1.35,NaN

In [54]:
laptops_df.tail(6)

,brand,model,ram,hd_type,hd_size,screen_size,price,processor_brand,processor_model,clock_speed,graphic_card_brand,graphic_card_size,os,weight,comments
161,Asus,X541UA-GO1345D,4,hdd,1024,15.6,27730,intel,i3 6th gen,2.0,intel,NaN,linux,1.84,NaN
162,Asus,A555LF,8,hdd,1024,15.6,39961,intel,i3 4th gen,1.7,nvidia,2.0,windows,2.30,NaN
163,Asus,X555LA-XX172D,4,hdd,500,15.6,28489,intel,i3 4th gen,1.9,intel,NaN,linux,2.30,NaN
164,Asus,X554LD,2,hdd,500,15.6,29199,intel,i3 4th gen,1.9,intel,1.0,linux,2.30,NaN
165,Asus,X550LAV-XX771D,2,hdd,500,15.6,29990,intel,i3 4th gen,1.7,intel,NaN,linux,2.50,NaN
166,Asus,X540LA-XX538T,4,hdd,1024,15.6,30899,intel,i3 5th gen,2.0,intel,NaN,windows,2.30,NaN

In [55]:
laptops_df.shape

(167, 15)

In [56]:
laptops_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   brand               167 non-null    object
 1   model               167 non-null    object
 2   ram                 167 non-null    int64
 3   hd_type             167 non-null    object
 4   hd_size             167 non-null    int64
 5   screen_size         167 non-null    float64
 6   price               167 non-null    int64
 7   processor_brand     167 non-null    object
 8   processor_model     167 non-null    object
 9   clock_speed         166 non-null    float64
 10  graphic_card_brand  163 non-null    object
 11  graphic_card_size   81 non-null     float64
 12  os                  167 non-null    object
 13  weight              160 non-null    float64
 14  comments            55 non-null     object
dtypes: float64(4), int64(3), object(8)
memory usage: 19.7+ KB

In [57]:
laptops_df.describe()

,ram,hd_size,screen_size,price,clock_speed,graphic_card_size,weight
count,167.000000,167.00000,167.000000,167.000000,166.000000,81.000000,160.000000
mean,6.898204,768.91018,14.775210,64132.898204,2.321084,52.160494,2.250813
std,3.787479,392.99080,1.376526,42797.674010,0.554187,444.134142,0.648446
min,2.000000,32.00000,10.100000,13872.000000,1.100000,1.000000,0.780000
25%,4.000000,500.00000,14.000000,35457.500000,1.900000,2.000000,1.900000
50%,8.000000,1024.00000,15.600000,47990.000000,2.300000,2.000000,2.200000
75%,8.000000,1024.00000,15.600000,77494.500000,2.600000,4.000000,2.600000
max,16.000000,2048.00000,17.600000,226000.000000,3.800000,4000.000000,4.200000

In [59]:
laptops_df.sort_values(by='price', ascending=False)

,brand,model,ram,hd_type,hd_size,screen_size,price,processor_brand,processor_model,clock_speed,graphic_card_brand,graphic_card_size,os,weight,comments
5,Apple,MacBook Pro (TouchBar),16,ssd,512,15.0,226000,intel,i7,2.70,intel,2.0,mac,2.5,NaN
90,Alienware,15 Notebook,16,hdd,1024,15.6,199000,intel,i7,2.60,nvidia,8.0,windows,3.5,Maximum Display Resolution : 1920 x 1080 pixel
96,Alienware,AW13R3-7000SLV-PUS,8,ssd,256,13.3,190256,intel,i7,3.00,nvidia,6.0,windows,2.6,13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
31,Acer,Predator 17,16,ssd,256,17.3,178912,intel,i7,2.60,nvidia,NaN,windows,4.2,Integrated Graphics
154,Microsoft,Surface Book CR9-00013,8,ssd,128,13.5,178799,intel,i5,1.80,intel,NaN,windows,1.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Acer,Aspire ES1-523,4,hdd,1024,15.6,19465,amd,A4-7210,1.80,amd,NaN,linux,2.4,NaN
100,Acer,A315-31-P4CRUN.GNTSI.002,4,hdd,500,15.6,18990,intel,pentium,1.10,intel,NaN,windows,NaN,NaN
108,Acer,Aspire ES-15 NX.GKYSI.010,4,hdd,500,15.6,17990,amd,A4-7210,1.80,amd,NaN,windows,2.4,NaN
83,Acer,A315-31CDC UN.GNTSI.001,2,ssd,500,15.6,17990,intel,Celeron,1.10,intel,NaN,windows,2.1,NaN
148,Acer,Aspire SW3-016,2,ssd,32,10.1,13872,intel,Atom Z8300,1.44,intel,NaN,windows,1.2,NaN

### 시리즈 분석

In [60]:
laptops_df["brand"].unique()

array(['Dell', 'Apple', 'Acer', 'HP', 'Lenovo', 'Alienware', 'Microsoft',
       'Asus'], dtype=object)

In [61]:
laptops_df['brand'].value_counts()

HP           55
Acer         35
Dell         31
Lenovo       18
Asus          9
Apple         7
Alienware     6
Microsoft     6
Name: brand, dtype: int64

In [62]:
laptops_df["brand"].describe()

count     167
unique      8
top        HP
freq       55
Name: brand, dtype: object